### ISSUE TITLE
"[coap] Fatal DTLS error: code 115" (not sure if this is a problem of pytradfri)

### ISSUE THREAD

**Issue by linuxlurak** [home-assistant-libs/pytradfri#176]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant:

`hass --version`
> 0.73.1

Linux homeautomation 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu Codename bionic

### Version of pytradfri

`pip3 list | grep pytradfri`

> pytradfri           5.5.1

### Expected behaviour

Have multiple tradfri gateways handled correctly

### Actual behaviour

Log gets flooded by "[coap] Fatal DTLS error: code 115". Only one gateway is handled by Home Assistant. Probably the first detected ist set up correctly. One gateway works; the other dosen't.

More details here: https://github.com/home-assistant/home-assistant/issues/15287

If there is need for a second gateway with some of you developers please contact me. I'm willing to donate some gateways.

**Comment by ggravlingen** [comment]
Does it work if you run pytradfri stand-alone? Let's try that first to see if the error is with pytradfri or Home Assistant.

**Comment by linuxlurak** [comment]
I think it looks good:

root@homeautomation:~# `python3 -i -m pytradfri 192.168.10.6`

> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15001']
> DEBUG:pytradfri.api.libcoap_api:Received: [65537,65538]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15001', 65537]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Living Lamp Back","9002":1501948147,"9020":1531743023,"9003":65537,"9054":0,"5750":2,"9019":1,"3":{"0":"IKEA of Sweden","6":1,"1":"TRADFRI bulb E27 opal 1000lm","3":"1.2.214","2":""},"3311":[{"5850":0,"5851":223,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15001', 65538]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"Living Lamp Shelf","9002":1501948184,"9020":1531743032,"9003":65538,"9054":0,"5750":2,"9019":1,"3":{"0":"IKEA of Sweden","6":1,"1":"TRADFRI bulb E27 W opal 1000lm","3":"1.2.214","2":""},"3311":[{"5850":0,"5851":223,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15004']
> DEBUG:pytradfri.api.libcoap_api:Received: [182259]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15005', <pytradfri.command.Command object at 0x7fb8894bd860>]
> DEBUG:pytradfri.api.libcoap_api:Received: [182259]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15010']
> DEBUG:pytradfri.api.libcoap_api:Received: []
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.6 get ['15011', '15012']
> DEBUG:pytradfri.api.libcoap_api:Received: {"9023":"1.tradfri.pool.ntp.org","9059":1531764041,"9060":"2018-07-16T18:00:41.064928Z","9062":0,"9077":28,"9061":0,"9029":"1.4.15","9107":1,"9081":"7e121d5204400027","9082":true,"9105":0,"9083":"926-68-687","9074":0,"9054":0,"9075":59,"9072":3,"9055":0,"9080":60,"9066":5,"9069":1530533253,"9073":25,"9071":1,"9078":1,"9076":10,"9106":0,"9079":0,"9092":0,"9093":0,"9200":"3d960f76-b272-4aa6-95b4-733328f6dbc9"}
> 
> Example commands:
> > devices
> > homekit_id
> > light.light_control.lights
> > api(light.light_control.set_dimmer(10))
> > api(light.light_control.set_dimmer(254))
> > api(light.light_control.set_xy_color(254))
> > api(lights[1].light_control.set_dimmer(20))
> > api(gateway.reboot())
> > groups
> > moods
> > tasks
> > dump_devices()
> > dump_all()
> >>>


`root@homeautomation:~# python3 -i -m pytradfri 192.168.10.5`

> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001']
> DEBUG:pytradfri.api.libcoap_api:Received: [65536,65540,65538,65539,65537]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001', 65536]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI motion sensor","9002":1530356320,"9020":1530356694,"5750":4,"9054":0,"9003":65536,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI motion sensor","2":"","3":"1.2.214","6":3,"9":60},"3300":[{"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001', 65540]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E27 opal 1000lm 4","9002":1530356679,"9020":1530443296,"5750":0,"9054":0,"9003":65540,"9019":0,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 opal 1000lm","2":"","3":"1.2.214","6":1},"15009":[{"5851":0,"5850":0,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001', 65538]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E27 W opal 1000lm 2","9002":1530356456,"9020":1531684185,"5750":2,"9054":0,"9003":65538,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 W opal 1000lm","2":"","3":"1.2.214","6":1},"3311":[{"5851":254,"5850":0,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001', 65539]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E27 W opal 1000lm 3","9002":1530356532,"9020":1531746160,"5750":2,"9054":0,"9003":65539,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 W opal 1000lm","2":"","3":"1.2.214","6":1},"3311":[{"5851":153,"5850":0,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15001', 65537]
> DEBUG:pytradfri.api.libcoap_api:Received: {"9001":"TRADFRI bulb E27 W opal 1000lm","9002":1530356387,"9020":1531746175,"5750":2,"9054":0,"9003":65537,"9019":1,"3":{"0":"IKEA of Sweden","1":"TRADFRI bulb E27 W opal 1000lm","2":"","3":"1.2.214","6":1},"3311":[{"5851":254,"5850":0,"9003":0}]}
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15004']
> DEBUG:pytradfri.api.libcoap_api:Received: [131073]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15005', <pytradfri.command.Command object at 0x7fa81b7abe10>]
> DEBUG:pytradfri.api.libcoap_api:Received: [131073]
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15010']
> DEBUG:pytradfri.api.libcoap_api:Received: []
> DEBUG:pytradfri.api.libcoap_api:Executing 192.168.10.5 get ['15011', '15012']
> DEBUG:pytradfri.api.libcoap_api:Received: {"9023":"1.tradfri.pool.ntp.org","9200":"0f651fdb-6498-4226-a891-7a17fe7f8081","9059":1531764118,"9105":0,"9080":60,"9072":3,"9071":1,"9060":"2018-07-16T18:01:58.018784Z","9107":1,"9062":0,"9061":0,"9075":59,"9029":"1.4.15","9081":"7e244d5204400030","9082":false,"9083":"N/A","9074":0,"9054":0,"9055":0,"9066":5,"9069":1530536387,"9073":25,"9076":10,"9092":0,"9077":28,"9078":1,"9093":0,"9079":0,"9106":0}
> 
> Example commands:
> > devices
> > homekit_id
> > light.light_control.lights
> > api(light.light_control.set_dimmer(10))
> > api(light.light_control.set_dimmer(254))
> > api(light.light_control.set_xy_color(254))
> > api(lights[1].light_control.set_dimmer(20))
> > api(gateway.reboot())
> > groups
> > moods
> > tasks
> > dump_devices()
> > dump_all()
> >>>

**Comment by Hate-Usernames** [comment]
AFAICT the aiocoap api uses a global credentials store. This means that connecting to a new gateway overwrites the credentials for the previous connection. Any subsequent connections to the first gateway are then rejected for using the wrong credentials. Fixing this will require a new version of the upstream aiocoap package (the development version already includes a new method of credential handling that may fix this) and some minor changes to the pytradfri implementation.

To confirm this, we first need to test connecting to multiple gateways in the same process using pytradfri's aiocoap (async) api. Could you run [this](https://gist.github.com/Hate-Usernames/14206914bd6750d16d724d23599d8c72) script in the following manner and post the results? The first two commands should print a list of the lights connected to that gateway and the third command I expect will give a similar DTLS error to the one you are seeing in home assistant (if all was well it would print two lists of lights, one for each gateway):
`python3 test_multiple_hosts.py 192.168.10.5`
`python3 test_multiple_hosts.py 192.168.10.6`
`python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6`

**Comment by linuxlurak** [comment]
I ran the test_multiple_hosts script. tinydtls module is missing. Do you have a source for this module? It seems it is gone from pip...

There is a mirror by baloob: https://github.com/balloob/tinydtls 

Would this mirror work?

**Comment by linuxlurak** [comment]
I actually had this version already lying around in my home directory. make fails though...

> ...
> dtls-server.c:199:25: error: dereferencing pointer to incomplete type ‘struct in6_pktinfo’
> ...
> <builtin>: recipe for target 'dtls-server' failed

**Comment by Hate-Usernames** [comment]
You're looking for [DTLSSocket](https://pypi.org/project/DTLSSocket/), see [installation](https://github.com/ggravlingen/pytradfri#1-installation).
You should also be able to `pip install 'pytradfri[async]'`

**Comment by linuxlurak** [comment]
Thanks! DTLSSocket was already satisfied. ` pip install 'pytradfri[async]` did the trick.

Here are the results:
`python3 test_multiple_hosts.py 192.168.10.5`

> decrypt_verify(): found 24 bytes cleartext
> decrypt_verify(): found 46 bytes cleartext
> decrypt_verify(): found 260 bytes cleartext
> decrypt_verify(): found 232 bytes cleartext
> decrypt_verify(): found 265 bytes cleartext
> decrypt_verify(): found 265 bytes cleartext
> decrypt_verify(): found 263 bytes cleartext
> [<65538 - TRADFRI bulb E27 W opal 1000lm 2 (TRADFRI bulb E27 W opal 1000lm)>, <65539 - TRADFRI bulb E27 W opal 1000lm 3 (TRADFRI bulb E27 W opal 1000lm)>, <65537 - TRADFRI bulb E27 W opal 1000lm (TRADFRI bulb E27 W opal 1000lm)>]
> Error in sys.excepthook:
> 
> Original exception was:

(there was nothing printed after 

> Original exception was:

...


`python3 test_multiple_hosts.py 192.168.10.6`

> decrypt_verify(): found 24 bytes cleartext
> decrypt_verify(): found 28 bytes cleartext
> decrypt_verify(): found 250 bytes cleartext
> decrypt_verify(): found 247 bytes cleartext
> [<65537 - Living Lamp Back (TRADFRI bulb E27 opal 1000lm)>, <65538 - Living Lamp Shelf (TRADFRI bulb E27 W opal 1000lm)>]
> Error in sys.excepthook:
> 
> Original exception was:


`python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6`

> Jul 17 21:20:49 ALRT 115 invalidate peer
> Fatal DTLS error: code 115
> Jul 17 21:20:49 WARN received alert, peer has been invalidated
> Exception CancelledError() can not be represented as errno, setting -1.
> Error in close: -1
> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 152, in request
>     result = yield from self._execute(api_commands)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 142, in _execute
>     _, res = yield from self._get_response(msg)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>     r = yield from pr.response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap/protocol.py", line 816, in _run_outer
>     yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap/protocol.py", line 865, in _run
>     blockresponse = yield from blockrequest.response
> OSError: [Errno -1] Unknown error -1
> Error in sys.excepthook:
> 
> Original exception was:

**Comment by Hate-Usernames** [comment]
Ok great. Don't worry about the exceptions, the key parts are that the first two printed a list of lights whereas the last one gave the same error you received in home assistant:

> ALRT 115 invalidate peer
> Fatal DTLS error: code 115

This is an authentication error and means we're sending the wrong credentials to the gateway. Now that we can reproduce the bug, we need to look at possible fixes. The easiest solution is to see whether the new credential handling in aiocoap can fix this. If you are willing to test this, you will need to:
1. Install the latest version of aiocoap. It is not on PyPI, so you'll need to grab the master branch from the [repository](https://github.com/chrysn/aiocoap).
2. Install a modified version of pytradfri from [here](https://github.com/Hate-Usernames/pytradfri/tree/update-aiocoap).
3. Rerun the script.

**Comment by linuxlurak** [comment]
Sure I'll test! Thanks for your help and guidance!

I installed from the repository like this (not sure if correct):
~/aiocoap# `python3 setup.py build`
~/aiocoap# `python3 setup.py install`
No errors appeard.

Then installed your modified version of pytradfri with the same commands.

Executing `python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6` now gives me:

> Jul 17 22:47:35 ALRT 115 invalidate peer
> Fatal DTLS error: code 115
> Jul 17 22:47:35 WARN received alert, peer has been invalidated
> Exception CancelledError() can not be represented as errno, setting -1.
> Error in close: -1
> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 152, in request
>     result = yield from self._execute(api_commands)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 142, in _execute
>     _, res = yield from self._get_response(msg)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>     r = yield from pr.response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap/protocol.py", line 816, in _run_outer
>     yield from cls._run(app_request, response, weak_observation, protocol, log, exchange_monitor_factory)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap/protocol.py", line 865, in _run
>     blockresponse = yield from blockrequest.response
> OSError: [Errno -1] Unknown error -1
> Error in sys.excepthook:
> 
> Original exception was:

**Comment by linuxlurak** [comment]
I suspect the script loads the wrong modules. I uninstalled pytradfri and aiocoap with `pip3 uninstall pytradfri` and `pip3 uninstall aiocoap` and installed the customized version like written above.

The result now is:

`python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6`

> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 152, in request
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 142, in _execute
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 728, in _run_outer
>     await cls._run(app_request, response, weak_observation, protocol, log)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 753, in _run
>     await protocol.find_remote_and_interface(app_request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
>     if await ri.fill_or_recognize_remote(message):
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/tokenmanager.py", line 170, in fill_or_recognize_remote
>     return await self.token_interface.fill_or_recognize_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/messagemanager.py", line 327, in fill_or_recognize_remote
>     remote = await self.message_interface.determine_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/transports/tinydtls.py", line 318, in determine_remote
>     dtlsparams = self.ctx.client_credentials.credentials_from_request(request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/credentials.py", line 281, in credentials_from_request
>     raise CredentialsMissingError("No suitable credentials for %s" % uri)
> aiocoap.credentials.CredentialsMissingError: No suitable credentials for coaps://192.168.10.5:5684/15001

Same on executing against only one gateway:
`python3 test_multiple_hosts.py 192.168.10.5`

> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 152, in request
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 142, in _execute
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 728, in _run_outer
>     await cls._run(app_request, response, weak_observation, protocol, log)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 753, in _run
>     await protocol.find_remote_and_interface(app_request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
>     if await ri.fill_or_recognize_remote(message):
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/tokenmanager.py", line 170, in fill_or_recognize_remote
>     return await self.token_interface.fill_or_recognize_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/messagemanager.py", line 327, in fill_or_recognize_remote
>     remote = await self.message_interface.determine_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/transports/tinydtls.py", line 318, in determine_remote
>     dtlsparams = self.ctx.client_credentials.credentials_from_request(request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/credentials.py", line 281, in credentials_from_request
>     raise CredentialsMissingError("No suitable credentials for %s" % uri)
> aiocoap.credentials.CredentialsMissingError: No suitable credentials for coaps://192.168.10.5:5684/15001

`python3 test_multiple_hosts.py 192.168.10.6`

> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 152, in request
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 142, in _execute
>   File "/usr/local/lib/python3.6/dist-packages/pytradfri-5.5.1-py3.6.egg/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 728, in _run_outer
>     await cls._run(app_request, response, weak_observation, protocol, log)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 753, in _run
>     await protocol.find_remote_and_interface(app_request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
>     if await ri.fill_or_recognize_remote(message):
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/tokenmanager.py", line 170, in fill_or_recognize_remote
>     return await self.token_interface.fill_or_recognize_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/messagemanager.py", line 327, in fill_or_recognize_remote
>     remote = await self.message_interface.determine_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/transports/tinydtls.py", line 318, in determine_remote
>     dtlsparams = self.ctx.client_credentials.credentials_from_request(request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/credentials.py", line 281, in credentials_from_request
>     raise CredentialsMissingError("No suitable credentials for %s" % uri)
> aiocoap.credentials.CredentialsMissingError: No suitable credentials for coaps://192.168.10.6:5684/15001

**Comment by Hate-Usernames** [comment]
You are still running the old pytradfri -- the line numbers in the errors should change if you are running the modified version.

I think the simplest method is to install them into the same directory as the script (python searches for modules starting with the current dir).
For the modified pytradfri you really just need [this folder](
https://github.com/Hate-Usernames/pytradfri/tree/update-aiocoap/pytradfri).

I'm able to run this locally with one gateway, but I can't test more than that.

**Comment by linuxlurak** [comment]
`python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6`

> Traceback (most recent call last):
>   File "test_multiple_hosts.py", line 74, in <module>
>     asyncio.get_event_loop().run_until_complete(run())
>   File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
>     return future.result()
>   File "test_multiple_hosts.py", line 68, in run
>     devices_commands = yield from apis[host](devices_command)
>   File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
>     result = yield from self._execute(api_commands)
>   File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 142, in _execute
>     _, res = yield from self._get_response(msg)
>   File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 92, in _get_response
>     r = yield from pr.response
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 728, in _run_outer
>     await cls._run(app_request, response, weak_observation, protocol, log)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 753, in _run
>     await protocol.find_remote_and_interface(app_request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/protocol.py", line 295, in find_remote_and_interface
>     if await ri.fill_or_recognize_remote(message):
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/tokenmanager.py", line 170, in fill_or_recognize_remote
>     return await self.token_interface.fill_or_recognize_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/messagemanager.py", line 327, in fill_or_recognize_remote
>     remote = await self.message_interface.determine_remote(message)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/transports/tinydtls.py", line 318, in determine_remote
>     dtlsparams = self.ctx.client_credentials.credentials_from_request(request)
>   File "/usr/local/lib/python3.6/dist-packages/aiocoap-0.4a1.post0-py3.6.egg/aiocoap/credentials.py", line 281, in credentials_from_request
>     raise CredentialsMissingError("No suitable credentials for %s" % uri)
> aiocoap.credentials.CredentialsMissingError: No suitable credentials for coaps://192.168.10.5:5684/15001

tradfri_standalone_psk.conf and test_multiple_hosts.py are in ~/pytradfri/  where a subdir is called pytradfri. Is there still a problem with my setup?

**Comment by Hate-Usernames** [comment]
These line numbers are not correct for the modified version (i.e. you are running the "old" version)
> File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 152, in request
> result = yield from self._execute(api_commands)
> File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 142, in _execute
> _, res = yield from self._get_response(msg)
> File "/root/pytradfri/pytradfri/api/aiocoap_api.py", line 92, in _get_response
> r = yield from pr.response

Perhaps the easiest thing to do is just to change the contents of
`/root/pytradfri/pytradfri/api/aiocoap_api.py`
to [this](https://raw.githubusercontent.com/Hate-Usernames/pytradfri/update-aiocoap/pytradfri/api/aiocoap_api.py).

**Comment by linuxlurak** [comment]
Thanks!

`python3 test_multiple_hosts.py 192.168.10.5 192.168.10.6`

> decrypt_verify(): found 24 bytes cleartext
> decrypt_verify(): found 44 bytes cleartext
> decrypt_verify(): found 261 bytes cleartext
> decrypt_verify(): found 258 bytes cleartext
> decrypt_verify(): found 230 bytes cleartext
> decrypt_verify(): found 263 bytes cleartext
> decrypt_verify(): found 263 bytes cleartext
> [<65538 - TRADFRI bulb E27 W opal 1000lm 2 (TRADFRI bulb E27 W opal 1000lm)>, <65539 - TRADFRI bulb E27 W opal 1000lm 3 (TRADFRI bulb E27 W opal 1000lm)>, <65537 - TRADFRI bulb E27 W opal 1000lm (TRADFRI bulb E27 W opal 1000lm)>]
> decrypt_verify(): found 24 bytes cleartext
> decrypt_verify(): found 26 bytes cleartext
> decrypt_verify(): found 248 bytes cleartext
> decrypt_verify(): found 245 bytes cleartext
> [<65537 - Living Lamp Back (TRADFRI bulb E27 opal 1000lm)>, <65538 - Living Lamp Shelf (TRADFRI bulb E27 W opal 1000lm)>]
> Error in sys.excepthook:
> 
> Original exception was:
> Error in sys.excepthook:
> 
> Original exception was:

**Comment by linuxlurak** [comment]
My offer still stands :) If one of you devs needs a second gateway I'm willing to donate one!

**Comment by ggravlingen** [comment]
Wasn't the conclusion here that the problem lies with the implementation in Home Assistant?

**Comment by linuxlurak** [comment]
Is it a problem of the [tradfri component](https://github.com/home-assistant/home-assistant/blob/ea2ff6aae32821b8faaa7e5eb00efce779ebac73/homeassistant/components/tradfri.py) of home assistant or the discovery component or something else?

**Comment by linuxlurak** [comment]
I posted some debug info here: https://github.com/home-assistant/home-assistant/pull/16768#issuecomment-423770333

The devs (@balloob ) over at home assistant told me it's a problem of pytradfri. Just to inform you.

**Comment by ggravlingen** [comment]
@balloob is one of the authors of pytradfri so he knows what he's talking about. :) Good to at least have a confirmation of where the error is.

**Comment by ggravlingen** [comment]
I won't be able to fix it myself but I've flagged the issue under help wanted. Hopefully someone needs it too and submits a PR that resolves the issue.

**Comment by Hate-Usernames** [comment]
Sorry, I've been a little snowed under recently so seemingly disappeared off the face of the world before this was solved. It's definitely an issue with pytradfri, but we really need an update to aiocoap to fix it properly.
The referenced aiocoap issue about the credentials framework along with the pytradfri patch mentioned earlier in this thread solves this. But it needs a new (pre-)release build of aiocop pushed to pypi with the credentials framework incorporated before we can include the fix in pytradfri.

**Comment by linuxlurak** [comment]
Best I can do is to test and report. Im no programmer... 

Thank you all for your efforts!

**Comment by njbuch** [comment]
Ping, I am very interested in this, anyone on it?

**Comment by linuxlurak** [comment]
I moved to zigbee2mqtt. At least for one of my gateways.  Perhaps I'll leave the other gateway behind too.

**Comment by MartinHjelmare** [comment]
This should be resolved in the latest version of pytradfri 7.0.0.

Home Assistant will use this updated version in 0.115.0.
