### ISSUE TITLE
Is is possible to manage groups using pytradfri?

### ISSUE THREAD

**Issue by grembo** [home-assistant-libs/pytradfri#226]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone

### Version of pytradfri
latest (b122263)

### Expected behaviour
be able to add devices to groups, create groups, remove groups

### Actual behaviour
no matter what I tried (based on my limited knowledge of the products), the only things I can change are group name and state and controlling individual devices. Modifying group members using put 15004/<groupid> has no effect (altering 9018:15002:9903), also, using the <//15004/add>;ct=0, and <//15004/remove>;ct=0, endpoints yielded no results. It would be really cool to be able to configure groups without installing the app/adding a phone to the network. Any pointers on how to get this done/debugged (assuming this is possible at all)?

**Comment by ggravlingen** [comment]
My view is that the app just sends coap commands so you should be able to control groups.

What I would do to try to solve this:
- Look at the content of a group (see the debug script), try to figure out the pattern of a group and add a new entity
- Setup wireshark and monitor the traffic to the gateway. The key on the router is the key for SSL.
- Search github for other implementations og Trådfri in other languagues and see if they're solved it.

**Comment by tranbert** [comment]
Command line for a fade out to zero w/ duration 30 seconds on group 131074 :  

coap-client -m put -u "ffe376******96dcb" -k "9J*******po" "coaps://192.168.0.36:5684/15004/131074" -e '{  "5712": 300, "5851": 0}'

**Comment by rbraken** [comment]
> ### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
> 
> stand-alone
> ### Version of pytradfri
> 
> latest ([b122263](https://github.com/ggravlingen/pytradfri/commit/b122263179cce00b70d505c4cb688e77a6613f51))
> ### Expected behaviour
> 
> be able to add devices to groups, create groups, remove groups
> ### Actual behaviour
> 
> no matter what I tried (based on my limited knowledge of the products), the only things I can change are group name and state and controlling individual devices. Modifying group members using put 15004/ has no effect (altering 9018:15002:9903), also, using the <//15004/add>;ct=0, and <//15004/remove>;ct=0, endpoints yielded no results. It would be really cool to be able to configure groups without installing the app/adding a phone to the network. Any pointers on how to get this done/debugged (assuming this is possible at all)?

add or remove a group from a device (bulb)

 cmd = "add"   or cmd="remove"

 myd = {}
  myd[ATTR_ID] = [dev.id]
  myd["9038"]  = grp.id"
  api(Command('put', [15004,cmd],myd))

See also issue 211
