### ISSUE TITLE
Any progress to the issue of running pytradfri under Windows?

### ISSUE THREAD

**Issue by Yaaman42** [home-assistant-libs/pytradfri#235]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Standalone
### Version of pytradfri
6.0.1
### Expected behaviour
Able to install and use with Python 3 under Windows 10
### Actual behaviour
Fails when trying to install DTLSsocket with a "File not found" error
[log.txt](https://github.com/ggravlingen/pytradfri/files/3317336/log.txt)

**Comment by Yaaman42** [comment]
Anyone?

**Comment by ggravlingen** [comment]
There are no activities from the maintainers of this repo and I have personally not heard of anyone else working on it.

**Comment by kanflo** [comment]
@Yaaman42 have you tried the following ([source](https://github.com/home-assistant/home-assistant/issues/10022)) 

`pip3` install DTLSSocket`

**Comment by Yaaman42** [comment]
Before going through the normal process for pyTradfri?

Den lör 13 juli 2019 08:08Johan Kanflo <notifications@github.com> skrev:

**Comment by fungiboletus** [comment]
A classic workaround for GNU/Linux apps which don't run on Windows is to use… Linux. With WSL (Windows Sublinux System) and/or Docker for Windows for example.

**Comment by Markus1748** [comment]
I'm fighting with this problem, too. 

pip install DTLSSocket always returns an file not found error.

When running pytradfri\example.async.py  I get error message "No transport could route message".
Is there any other "transportation" lib than DTLSsocket?

Sorry, I really need native Windows to integrate this into my Home Control system ...

**Comment by Yaaman42** [comment]
I feel your pain....

**Comment by ggravlingen** [comment]
It’s not something we’re working on from the side of the maintainers of this repo, or plan to work on.
