### ISSUE TITLE
Catch aiocoap.error.NetworkError

### ISSUE THREAD

**Issue by balloob** [home-assistant-libs/pytradfri#237]
### Version of pytradfri
6.0.1

In #189 we started catching OSError because it could be raised from aiocoap. Aiocoap is starting to catch these errors themselves and wrapping them in `aiocoap.error.NetworkError`. So we need to update our implementation to catch NetworkError besides OSError (not instead off just yet, as not all places have been wrapped yet in aiocoap).

More info https://github.com/chrysn/aiocoap/issues/124

**Comment by ggravlingen** [comment]
To be overly clear, you mean amending this line?
https://github.com/ggravlingen/pytradfri/blob/b63e1d5c79676b7a0b3798bfb4774fb60f51c084/pytradfri/api/aiocoap_api.py#L102

**Comment by lwis** [comment]
Yup, we also need to update our aiocoap (maybe requesting a new PyPi release if there hasn't already been one).

**Comment by MartinHjelmare** [comment]
Closed in #287.
