### ISSUE TITLE
pytradfri mains power

### ISSUE THREAD

**Issue by jwevandijk** [home-assistant-libs/pytradfri#254]
Running pytradfri on rasbian buster and ubuntu 19.04.
Is there a way to detect whether the mains of a lightbulb is switched on and a socket is plugged in?
BTW thanks for making pytradgfi

**Comment by ggravlingen** [comment]
Not sure what you mean exactly, but have you tried the reachable attribute?

**Comment by jwevandijk** [comment]
What I mean is e.g. an IKEA Tradfri light bulb that is connected to the mains 230V power via a mechanical switch.
Yes I had a look at the reachable attribute but that seems unreliable. If the mains switch is off for hours or if the hub is restarted by unplugging, dev.reachable changes to False; gateway.reboot() seems to do nothing. Indeed when the mains is switched on after a restart of the hub, dev.reachable immediately changes to True again.
