### ISSUE TITLE
color conversion fails 

### ISSUE THREAD

**Issue by sgauert** [home-assistant-libs/pytradfri#265]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
I use it stand alone.

### Version of pytradfri
cloned today  
aiocoap==0.4a1
astroid==2.3.3
colormath==3.0.0
cycler==0.10.0
Cython==0.29.14
decorator==4.4.1
DTLSSocket==0.1.7
imageio==2.6.1
isort==4.3.21
kiwisolver==1.1.0
lazy-object-proxy==1.4.3
matplotlib==3.1.3
mccabe==0.6.1
networkx==2.4
numpy==1.18.1
Pillow==7.0.0
pylint==2.4.4
pyparsing==2.4.6
python-dateutil==2.8.1
PyWavelets==1.1.1
scikit-image==0.16.2
scipy==1.4.1
six==1.14.0
typed-ast==1.4.1
typing==3.7.4.1
wrapt==1.11.2
### Expected behaviour
I was trying to change the light color but I keep getting errors. 
I got to admit I don't get your color conversion.

Lets say I want white:
`r,g,b = 255,255,255
xyz = convert_color(sRGBColor(r,g,b), XYZColor, target_illuminant='d65')
`

### Actual behaviour
`xyz then is:
XYZColor(xyz_x=498944.6380412454,xyz_y=524946.6193601568,xyz_z=571651.0337770719)`

Which fails because it should be between 0 and 65536.
What am I missing here?

**Comment by ggravlingen** [comment]
We basically mirror the functionality of the gateway, no conversion is done by this lib. I’ve played around about with colors as well but didn’t get how conversion works.

This is not a solvable issue, closing.
