### ISSUE TITLE
Temperature set while light off ignored even after light turned on

### ISSUE THREAD

**Issue by jeremyvisser** [home-assistant-libs/pytradfri#270]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)

Normally I use with Home Assistant (0.110.1), but to reproduce this issue I used pytradfri standalone (`python -i -m pytradfri`).

### Version of pytradfri

Latest HEAD at time of writing (a0203ac2c15668100b45c35b61de3508e384dafd)

### Expected behaviour

I can set my light temperature fine when it's on:

```python
>>> uplight = lights[2]
>>> api(uplight.light_control.set_state(1)) # Turn on
>>> api(uplight.light_control.set_color_temp(250)) # SUCCESS: light becomes cool
DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 250}]}
DEBUG:pytradfri.api.libcoap_api:Received: 
>>> api(uplight.light_control.set_color_temp(454)) # SUCCESS: light becomes warm
DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 454}]}
DEBUG:pytradfri.api.libcoap_api:Received: 
```

Ideally, I would like to set the temperature when it's off so it's at the correct temperature when I turn it on:

```python
>>> api(uplight.light_control.set_color_temp(454)) # Set to warm while light is on
>>> api(uplight.light_control.set_state(0)) # Turn off
>>> api(uplight.light_control.set_color_temp(250)) # Set to cool while light is off
>>> api(uplight.light_control.set_state(1)) # Turn on, expect light to be cool, but is actually warm
```

I would expect the light to be cool (temperature 250) when it turns on, but is actually warm (remembers old temperature 454).

### Actual behaviour

There are two main differences between actual and expected behaviour:

1. Light turns on with previous temperature (if turned off at temperature 454, it turns on at temperature 454, even if temperature 250 was set while it was off)
1. Attempting to work around the issue, if I try to set the desired temperature a second time:

   ```python
   >>> api(uplight.light_control.set_color_temp(454)) # Set to warm while light is on
   DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 454}]}
   DEBUG:pytradfri.api.libcoap_api:Received: 
   >>> api(uplight.light_control.set_state(0)) # Turn off
   >>> api(uplight.light_control.set_color_temp(250)) # Set to cool while light is off
   DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 250}]}
   DEBUG:pytradfri.api.libcoap_api:Received: 
   >>> api(uplight.light_control.set_state(1)) # Turn on, expect light to be cool
   >>> api(uplight.light_control.set_color_temp(250)) # Attempt to set temperature *again*
   DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 250}]}
   DEBUG:pytradfri.api.libcoap_api:Received: 
   ```

   The light still does not respond to the new temperature. In fact, no matter how many times I set the desired temperature, it will not respond.

   Since the light is on, if I set *any* temperature other than the one I was trying to set, e.g. 251:

   ```python
   >>> api(uplight.light_control.set_color_temp(251)) # Set to different than desired temperature
   DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 251}]}
   DEBUG:pytradfri.api.libcoap_api:Received: 
   >>> api(uplight.light_control.set_color_temp(250)) # SUCCESS: light becomes desired temperature
   DEBUG:pytradfri.api.libcoap_api:Executing tradfri.local put ['15001', 65539]: {'3311': [{'5711': 250}]}
   DEBUG:pytradfri.api.libcoap_api:Received: 
   ```

   Then the light correctly becomes the desired temperature.

I should note that the Moods feature in the official IKEA Home Smart app does not suffer from this problem. If I turn the lights off at one temperature, then activate a mood with another temperature (e.g. activate mood Focus; turn lights off; activate mood Relax), the lights correctly jump to the new temperature immediately.

The original problem I was trying to solve was replicating the Moods functionality inside Home Assistant by using Scenes. Because of this bug, if I set a Home Assistant Scene while the lights are off, the lights turn on with the incorrect temperature.

**Comment by ggravlingen** [comment]
It’s interesting that the mood feature in the app does that. Have you tried chaining two commands together before sending them to the API call?

**Comment by jeremyvisser** [comment]
I'm willing to try, but can you please clarify what you can by "chaining"? I don't see any mention of this in the docs or code:

https://github.com/ggravlingen/pytradfri/search?q=chain

There are only two search results, one which is unrelated, and another this very issue.

**Comment by ggravlingen** [comment]
I was thinking about something like what is done here: https://github.com/home-assistant/core/blob/b15caf31a97cb136078f1c89b36372492288b644/homeassistant/components/tradfri/light.py#L178

But I realise that pytradfri might have to be updated to make that work.

**Comment by jeremyvisser** [comment]
While I’m not really familiar enough with your codebase to do this, I did manage to try out your suggestion using the command-line `coap-client`.

I have found that I’m successfully able to set the light brightness and temperature combined (as long as I don't specify a transition; specifying a transition causes it to ignore brightness if temperature is different).

Example:

```bash
$ c() {
  coap-client -u ${username?} -k ${key?} coaps://192.168.23.7:5684/15001/65542 -m put -e $1
}

# Turn light off:
$ c '{"3311": [{"5850": 0}]}' # off

# Now, set both at the same time:
$ c '{"3311": [{"5851": 1, "5711": 454}]}' # bright 1%, orange
# RESULT: works, light is 1%, orange

# Again, turn off:
$ c '{"3311": [{"5850": 0}]}' # off

# Set both again:
$ c '{"3311": [{"5851": 254, "5711": 250}]}' # bright 100%, white
# RESULT: works, light is 100%, white
```

So your suggestion of combining into a single request when turning on works fine.

Using `coap-client`, I can reproduce the above issue, where if I attempt to set the temperature while the light is off, it will ignore that temperature until it changes:

```bash
# Setup, set light 100%, white, and turn off:
$ c '{"3311": [{"5851": 254, "5711": 250}]}' # bright 100%, white
$ c '{"3311": [{"5850": 0}]}' # off

# Now, attempt to set orange while off:
$ c '{"3311": [{"5711": 454}]}' # orange     

# Turn on, expect orange:
$ c '{"3311": [{"5850": 1}]}' # on
# RESULT: fails, light is white, but expected orange

# Attempt to set orange again:
$ c '{"3311": [{"5711": 454}]}' # orange
# RESULT: fails, light is stuck on white

# Attempt to set slightly different orange:
$ c '{"3311": [{"5711": 400}]}' # slightly different orange
# RESULT: succeeds, light changes colour to slightly different orange

# Now go back to originally desired orange:
$ c '{"3311": [{"5711": 454}]}' # orange
# RESULT: succeeds, light is orange
```

So the TRÅDFRI system is fairly picky about the API calls it wants and the order it should receive them.

As a user of the library, or as a Home Assistant user which is a general tool and can’t reasonably incorporate quirks for every device, I would hope that the pytradfri library can shield some of this complexity and help make this smoother.

Maybe this is already possible, but I couldn’t figure it out because the documentation is quite limited, but it sounds like we need a way to set the colour temperature and brightness in a single call, e.g.:

```python
lights[0].light_control.set_light(color_temp=454, brightness=254)
lights[0].light_control.set_light(color_temp=250, brightness=1)
```

Or along those lines. I’m sure the API is the way it is for a good reason, and I’m coming into this from a very newbie standpoint, so I’m more than happy to be educated on this if I’m overlooking things.

**Comment by n21brown** [comment]
I have a feeling this is a firmware change within a bulb or the gateway. 

I've been using a bash script to send coap commands to my devices to set them to cool white in the morning and warm white in the early evening.  This worked perfectly until recently (cant confirm when as yet) but I noticed that that bulbs stopped switching when off.

**Comment by ggravlingen** [comment]
@jeremyvisser it's been a while since I dabbled with colors and Tradfri, but I remember that they IKEA bulbs didn't have the exact color range as the Hue bulbs, for instance. That might be why you are not getting the expected orange color.

Regarding your question on:
```
lights[0].light_control.set_light(color_temp=454, brightness=254)
lights[0].light_control.set_light(color_temp=250, brightness=1)
```

Did you try this?
```
command = [light.light_control.set_hex_color('efd275'), light.light_control.set_dimmer(254)]
await api(command)
```

**Comment by jeremyvisser** [comment]
I would dearly love to try out your suggestion, but unfortunately I am currently suffering from an unrelated error that I can’t figure out since syncing to latest HEAD:

```
% python3 -i -m pytradfri tradfri.narnia.network
DEBUG:pytradfri.api.libcoap_api:Executing tradfri.narnia.network get ['15001']
DEBUG:pytradfri.api.libcoap_api:Received: 
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jeremy/Code/pytradfri/pytradfri/__main__.py", line 73, in <module>
    devices_commands = api(gateway.get_devices())
  File "/home/jeremy/Code/pytradfri/pytradfri/api/libcoap_api.py", line 94, in request
    return self._execute(api_commands, timeout=timeout)
  File "/home/jeremy/Code/pytradfri/pytradfri/api/libcoap_api.py", line 88, in _execute
    api_command.result = _process_output(return_value, parse_json)
  File "/home/jeremy/Code/pytradfri/pytradfri/command.py", line 77, in result
    self._result = self._process_result(value)
  File "/home/jeremy/Code/pytradfri/pytradfri/gateway.py", line 77, in process_result
    return [self.get_device(dev) for dev in result]
TypeError: 'NoneType' object is not iterable
```

I was trying with revision 918185c44ae18e5e7648c6bf602285985022332d. As soon as I figure it out, I’ll try your suggestion, but haven’t had enough time or inspiration to figure out what’s broken.

**Comment by ggravlingen** [comment]
Hmm, odd. Did you notice there has been an update in the requirements so you might need to reinstall dependencies.

**Comment by jeremyvisser** [comment]
The requirements were fine. I was kind of puzzled for a while, until I decided to dump the traffic in Wireshark, where Wireshark printed out a fatal alert saying "Unknown PSK Identity". Even though my `tradfri_standalone_psk.conf` was populated, evidently the gateway must have recycled the key, so regenerating a new PSK seemed to fix the issue in my previous comment (https://github.com/home-assistant-libs/pytradfri/issues/270#issuecomment-700387133).

Also, regarding your comment about combining API commands, I did find I was able to reproduce the issue same as before when combined.

Based on the debug output, it appears that pytradfri itself sends the commands serially over CoAP, even when I combine them like you suggested. So I don't think combined commands in and of themselves solve the issue.

As found before, the order the commands are sent is significant. Using your method:

```
>>> api(light.light_control.set_dimmer(0)) # turn light off
>>> api([light.light_control.set_color_temp(250), light.light_control.set_dimmer(254)])
# Expect: bright white light
# Actual: bright white light

>>> api(light.light_control.set_dimmer(0)) # turn light off
>>> api([light.light_control.set_color_temp(454), light.light_control.set_dimmer(100)])
# Expect: dim orange light
# Actual: dim white light (broken!)
```

However, if I reverse the order of `set_dimmer` and `set_color_temp`, the result changes:

```
>>> api(light.light_control.set_dimmer(0)) # turn light off
>>> api([light.light_control.set_dimmer(254), light.light_control.set_color_temp(250)])
# Expect: bright white light
# Actual: bright white light

>>> api(light.light_control.set_dimmer(0)) # turn light off
>>> api([light.light_control.set_dimmer(100), light.light_control.set_color_temp(454)])
# Expect: dim orange light
# Actual: dim orange light (works!)
```

This is more or less the same finding as the O.P. description. When combining commands with `set_color_temp` followed by `set_dimmer`, the colour temp is sent while the bulb is off (hence ignored). But with the reverse order, the dimmer is set (bulb turns on), and the colour temp gets accepted.

This is evidently a low–level quirk of the bulbs. As stated before, I believe the pytradfri could offer a better API by having an understanding of the current and desired lightbulb state, and sending the right CoAP commands to the bulb in the order it's likely to accept them.

**Comment by ggravlingen** [comment]
You are right, the commands seem to be sent in a sequential order. Re-writing that part of the API is not something we’ve discussed to do but we would happily take a pull request with the proposed changes to the API. 😊
