### ISSUE TITLE
set_hsb method at the Group doesn't change colors correctly

### ISSUE THREAD

**Issue by selimonat** [home-assistant-libs/pytradfri#290]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
stand-alone

### Version of pytradfri
7

### Backend used (aiocoap, libcoap)
libcoap

### Expected behaviour
I wrote few wrapper functions that are using the `set_hsb` method of either the Light or Group classes.

Whether it is Light or Group, I expect the color of the lights to be the same irrespective of whether I use a Group or Light class.
```
# Situation 1)
a.set_hsb_color(['Light'],[0.4,1,1])
['15001', 65571]
{'5708': 65279, '5707': 26214, '5851': 254}
# Situation 2)
a.set_hsb_color(['Group'],[0.4,1,1])
['15004', 131090]
{'5708': 65279, '5707': 26214, '5851': 254}
```

### Actual behaviour

In the situation 1) I change the HSB value using the `set_hsb` of the Light class and it actually changes the colors correctly. But in situation 2), where I use the `set_hsb` method of the Group object, the colors do not change correctly.

**Comment by ggravlingen** [comment]
What happened if you try to do the same in your IKEA app? The methods that set color look the same and just sends the commands to the gateway. We don’t do any transformation of colors along the way either.
