### ISSUE TITLE
Change lights' brightness at background (without turning State to On)

### ISSUE THREAD

**Issue by selimonat** [home-assistant-libs/pytradfri#292]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
standalone

### Version of pytradfri
918185c44ae18e5e7648c6bf602285985022332d
### Backend used (aiocoap, libcoap)
libcoap
### Expected behaviour

I am looking for a workflow to change lamp's brightness (or color too in that respect) without turning switching the state ON. Basically, i would like to set the brightness and color for the lamp for when the lamp will be turned on. 

### Actual behaviour

For some colored tradfri lamps I can set_xy_color() on the "background", meaning the changes I incurred take effect once the light is explicitely turned on. But for other lamps I was not able to get this done. I would appreciate if somebody has a clue, as this seems to me one fundamental way for automating the light patterns at home... For example, when I wake up for drinking water at 3 am, I prefer the lights to be dimmed when triggered with motion sensors...

**Comment by ggravlingen** [comment]
For the bulbs that you can not set color state on, are they also of the IKEA-brand?

**Comment by selimonat** [comment]
Yes. 


This is for `<65600 - ColorDome (TRADFRI bulb E27 CWS opal 600lm)>`:

```
# Turn on ColorDome 
a.run(a.lights["ColorDome"].light_control.set_state(True)) 
#  Turn off ColorDome
a.run(a.lights["ColorDome"].light_control.set_state(False)) 
# state becomes Off:
a.get_lights()["ColorDome"].light_control.lights                    

[<Light #0 - name: ColorDome, **state: off**, dimmer: 134, hex_color: 0, xy_color: (12000, 60000), hsb_xy_color: (21760, 65279, 134, 12000, 60000), supported features: 29 >]

# set color while state is off
a.run(a.lights["ColorDome"].light_control.set_xy_color(12000,40000))

# xy_color updates, state stays Off ==> Nice!
a.get_lights()["ColorDome"].light_control.lights                    

[<Light #0 - name: ColorDome, **state: off**, dimmer: 134, hex_color: 0, **xy_color: (12000, 40000)**, hsb_xy_color: (25620, 65279, 134, 12000, 40000), supported features: 29 >]
```

Let me do the same with a `<65604 - DinnerRoom (TRADFRI bulb E27 WS opal 980lm)>`:

```
a.get_lights()["DinnerRoom"].light_control.lights

[<Light #0 - name: DinnerRoom, state: off, dimmer: 200, hex_color: 0, xy_color: (25000, 43000), hsb_xy_color: (None, None, 200, 25000, 43000), supported features: 23 >]

# let me set hsb to some values
a.run(a.lights["DinnerRoom"].light_control.set_hsb(240,240,240)) 

# did it work?
a.get_lights()["DinnerRoom"].light_control.lights

# yes it worked but state switched to ON as well ==> Not nice.
[<Light #0 - name: DinnerRoom, state: **on**, dimmer: 240, hex_color: 0, xy_color: (20449, 21478), hsb_xy_color: (None, None, **240**, 20449, 21478), supported features: 23 >] 
```

**Comment by ggravlingen** [comment]
Hmm, odd. But I’m not sure this is due to the library if you can replicate the same behaviors every time for bulb 1. It could be that the different bulbs operate in different ways.
