### ISSUE TITLE
observing dimmers / motion sensors

### ISSUE THREAD

**Issue by perericr** [home-assistant-libs/pytradfri#294]
Using master pytradfri as standalone, with backend libcoap.

I am looking in the documentation and in the device objects for a way to get either event data or status from dimmers and motions sensors. Getting status is possible for lights, but it would be nice if it would be possible for controlling devices. 

Expected behaviour: Either
1. Documentation that this is not possible (or just not implemented yet)
2. Implementation and documentation of some parameter for the callback, showing if a click was "on" or "off" for example.
3. Implementation and documentation of status structure for each device containing last event, if that is how it works

Wishlist, of course.
I tried to find a user och dev mailing list or contact address, but none found so posting as wishlist issue.

**Comment by ggravlingen** [comment]
I actually haven't looked into this in a while but it hasn't been supported by the gateway, that's why the library doesn't support it. But the gateway has since been updated with new versions. Could I ask you to please have a look and see if you can observe changes to a motion sensor in your setup?

**Comment by perericr** [comment]
Thanks. I do get a callback when starting to observe motion sensors, but nothing for any sensing event. I *do* however get a callback for button presses when observing dimmers, even if there is no information on which button was pressed.

I can (as expected) also watch a light controlled by the motion sensor. I suppose that is how to do for now if getting readings from a motion sensor - setup a dummy light or on/off switch and watch that device.

The gateway is running firmware 1.11.51.

**Comment by ggravlingen** [comment]
Thanks for looking into this. Seems like there is still no support then. 😔
