### ISSUE TITLE
Blinds battery status is missed 

### ISSUE THREAD

**Issue by kkoksvik** [home-assistant-libs/pytradfri#298]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant OS on Pi

### Version of pytradfri
Latest Home Assistant not Beta

### Expected behaviour
I would expect to find referenses to Battery in blinds related code

### Actual behaviour
I can not find blinds battery status in Home assistant or in pytrådfri code

**Comment by ggravlingen** [comment]
Pytradfi allows watching the battery status of a blind as it is exposed for a device in the API [here](https://github.com/home-assistant-libs/pytradfri/blob/011f4880a776ee2078e6a4540463eb6ba65ca8b1/pytradfri/device/__init__.py#L146).

Home Assistant however currently does not expose this information.
