### ISSUE TITLE
Performing a request disconnect my other apps/applications

### ISSUE THREAD

**Issue by geluyan** [home-assistant-libs/pytradfri#303]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
I'm developing my own API engine with FastAPI and an Angular UI. All in docker containers, hosted on a kubernetes cluster and with iPads on my walls connecting to the Angular application.

### Version of pytradfri

Upgraded to 7.0.6

### Backend used (aiocoap, libcoap)

libcoap

### Expected behaviour

Using multiple iPads and the original Ikea APP without timeouts.

### Actual behaviour

When I open the Ikea APP, I can control my lights. When I start my API engine, I get a timeout on the original Ikea APP. It happens when I run through the groups. When using multiple iPad with my own interface, the same behaviour happens.

```
for group in self.api(self.gateway.get_groups()):
   print(group)
   self.api(group, timeout=1)  # Running this causes the original Ikea APP to timeout
```

Complete code snippet:
```
CONFIG_FILE = "tradfri_standalone_psk.conf"
conf = load_json(CONFIG_FILE)

try:
    identity = conf[os.environ["TRADFRI_HOST"]].get("identity")
    psk = conf[os.environ["TRADFRI_HOST"]].get("key")
    api_factory = APIFactory(host=os.environ["TRADFRI_HOST"], psk_id=identity, psk=psk)
except KeyError:
    identity = uuid.uuid4().hex
    api_factory = APIFactory(host=os.environ["TRADFRI_HOST"], psk_id=identity)

    try:
        psk = api_factory.generate_psk(os.environ["TRADFRI_KEY"])
        print("Generated PSK: ", psk)

        conf[os.environ["TRADFRI_HOST"]] = {"identity": identity, "key": psk}
        save_json(CONFIG_FILE, conf)
    except AttributeError:
        raise PytradfriError(
            "Please provide the 'Security Code' on the "
            "back of your Tradfri gateway using the "
            "-K flag."
        )

self.api = api_factory.request

for group in self.api(self.gateway.get_groups()):
   print(group)
   self.api(group, timeout=1) # Running this causes the original Ikea APP to timeout
```

**Comment by ggravlingen** [comment]
Does it work if you run the app on two separate iPads?

**Comment by geluyan** [comment]
I've already a version running on a single ipad and even with a single instance running, I'm getting timeouts. As long I have that one ipad polling the device status every 10 seconds, the ikea app disconnects. I have to close my app on the ipad to make sure the ikea app works decent.

It was easy to replicate:

1. Open Ikea app -> Everything works
2. Execute my own code -> It works
3. Couple second later the ikea app disconnects
4. Go back to step one

It looks like my own code `self.api(group, timeout=1) # Running this causes the original Ikea APP to timeout` hijacks the connections ore something.

**Comment by geluyan** [comment]
More info:

When the first instance performs a request and all devices in this case are gathered (sleep of 1 seconds between each device command) and a second instance performs the same request, the first request gets a timeout. This also explains why the Ikea app has the same issue.

When 2 instances request information from the gateway at the same time, one of them will get a timeout.
