### ISSUE TITLE
Can't install Pytradfri

### ISSUE THREAD

**Issue by ymestechwey** [home-assistant-libs/pytradfri#308]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant on TrueNas Jail
### Version of pytradfri
7.0.6
### Actual behaviour
Anyone can tell me how to fix this?

```txt
root@homeassistant:~ # service homeassistant install --no-cache-dir --force-reinstall "pytradfri[async]==7.0.6"
Collecting pytradfri[async]==7.0.6
  Downloading pytradfri-7.0.6-py3-none-any.whl (30 kB)
Collecting aiocoap==0.4b3; extra == "async"
  Downloading aiocoap-0.4b3.tar.gz (178 kB)
     |████████████████████████████████| 178 kB 6.1 MB/s
Collecting DTLSSocket==0.1.12; extra == "async"
  Downloading DTLSSocket-0.1.12.tar.gz (150 kB)
     |████████████████████████████████| 150 kB 8.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting Cython
  Downloading Cython-0.29.22-py2.py3-none-any.whl (980 kB)
     |████████████████████████████████| 980 kB 4.0 MB/s
Building wheels for collected packages: aiocoap, DTLSSocket
  Building wheel for aiocoap (setup.py) ... done
  Created wheel for aiocoap: filename=aiocoap-0.4b3-py3-none-any.whl size=190274 sha256=e357f8fe75c37fdc442aa7dae74b2b2bb7ba34528ac9076dd7b3d461e0a9cb9a
  Stored in directory: /tmp/pip-ephem-wheel-cache-f0v9or79/wheels/4b/7c/8b/002a6f0cfc24a00011d4b8a32b88ec09f3798195f55564ef61
  Building wheel for DTLSSocket (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/share/homeassistant/bin/python3.8 /usr/local/share/homeassistant/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmp4ggmemjm
       cwd: /tmp/pip-install-po4n2508/dtlssocket
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.freebsd-12.2-RELEASE-p3-amd64-3.8
  creating build/lib.freebsd-12.2-RELEASE-p3-amd64-3.8/DTLSSocket
  copying DTLSSocket/__init__.py -> build/lib.freebsd-12.2-RELEASE-p3-amd64-3.8/DTLSSocket
  copying DTLSSocket/DTLSSocket.py -> build/lib.freebsd-12.2-RELEASE-p3-amd64-3.8/DTLSSocket
  running build_ext
  autom4te-2.69: need GNU m4 1.4 or later: /usr/local/bin/gm4
  Running: autoconf
  Traceback (most recent call last):
    File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/share/homeassistant/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 216, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 202, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 253, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 27, in <module>
      setup(
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-6t_fcp7e/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 21, in run
      run_command(command)
    File "setup.py", line 12, in run_command
      subprocess.check_call(args, cwd=os.path.join(os.path.dirname(__file__), "DTLSSocket","tinydtls"))
    File "/usr/local/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['autoconf']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for DTLSSocket
Successfully built aiocoap
Failed to build DTLSSocket
ERROR: Could not build wheels for DTLSSocket which use PEP 517 and cannot be installed directly
```

**Comment by MartinHjelmare** [comment]
Do you have `autoconf` installed?

**Comment by ymestechwey** [comment]
> Do you have `autoconf` installed?

Yes I do,

root@homeassistant:~ # pkg list autoconf
/usr/local/bin/autoconf-2.69
/usr/local/bin/autoheader-2.69
/usr/local/bin/autom4te-2.69
/usr/local/bin/autoreconf-2.69
/usr/local/bin/autoscan-2.69
/usr/local/bin/autoupdate-2.69
/usr/local/bin/ifnames-2.69
/usr/local/man/man1/autoconf-2.69.1.gz
/usr/local/man/man1/autoheader-2.69.1.gz
/usr/local/man/man1/autom4te-2.69.1.gz
/usr/local/man/man1/autoreconf-2.69.1.gz
/usr/local/man/man1/autoscan-2.69.1.gz
/usr/local/man/man1/autoupdate-2.69.1.gz
/usr/local/man/man1/config.guess-2.69.1.gz
/usr/local/man/man1/config.sub-2.69.1.gz
/usr/local/man/man1/ifnames-2.69.1.gz
/usr/local/share/autoconf-2.69/Autom4te/C4che.pm
/usr/local/share/autoconf-2.69/Autom4te/ChannelDefs.pm
/usr/local/share/autoconf-2.69/Autom4te/Channels.pm
/usr/local/share/autoconf-2.69/Autom4te/Configure_ac.pm
/usr/local/share/autoconf-2.69/Autom4te/FileUtils.pm
/usr/local/share/autoconf-2.69/Autom4te/General.pm
/usr/local/share/autoconf-2.69/Autom4te/Getopt.pm
/usr/local/share/autoconf-2.69/Autom4te/Request.pm
/usr/local/share/autoconf-2.69/Autom4te/XFile.pm
/usr/local/share/autoconf-2.69/INSTALL
/usr/local/share/autoconf-2.69/autoconf/autoconf.m4
/usr/local/share/autoconf-2.69/autoconf/autoconf.m4f
/usr/local/share/autoconf-2.69/autoconf/autoheader.m4
/usr/local/share/autoconf-2.69/autoconf/autoscan.m4
/usr/local/share/autoconf-2.69/autoconf/autotest.m4
/usr/local/share/autoconf-2.69/autoconf/autoupdate.m4
/usr/local/share/autoconf-2.69/autoconf/c.m4
/usr/local/share/autoconf-2.69/autoconf/erlang.m4
/usr/local/share/autoconf-2.69/autoconf/fortran.m4
/usr/local/share/autoconf-2.69/autoconf/functions.m4
/usr/local/share/autoconf-2.69/autoconf/general.m4
/usr/local/share/autoconf-2.69/autoconf/go.m4
/usr/local/share/autoconf-2.69/autoconf/headers.m4
/usr/local/share/autoconf-2.69/autoconf/lang.m4
/usr/local/share/autoconf-2.69/autoconf/libs.m4
/usr/local/share/autoconf-2.69/autoconf/oldnames.m4
/usr/local/share/autoconf-2.69/autoconf/programs.m4
/usr/local/share/autoconf-2.69/autoconf/specific.m4
/usr/local/share/autoconf-2.69/autoconf/status.m4
/usr/local/share/autoconf-2.69/autoconf/types.m4
/usr/local/share/autoconf-2.69/autom4te.cfg
/usr/local/share/autoconf-2.69/autoscan/autoscan.list
/usr/local/share/autoconf-2.69/autotest/autotest.m4
/usr/local/share/autoconf-2.69/autotest/autotest.m4f
/usr/local/share/autoconf-2.69/autotest/general.m4
/usr/local/share/autoconf-2.69/autotest/specific.m4
/usr/local/share/autoconf-2.69/config.guess
/usr/local/share/autoconf-2.69/config.sub
/usr/local/share/autoconf-2.69/elisp-comp
/usr/local/share/autoconf-2.69/install-sh
/usr/local/share/autoconf-2.69/m4sugar/foreach.m4
/usr/local/share/autoconf-2.69/m4sugar/m4sh.m4
/usr/local/share/autoconf-2.69/m4sugar/m4sh.m4f
/usr/local/share/autoconf-2.69/m4sugar/m4sugar.m4
/usr/local/share/autoconf-2.69/m4sugar/m4sugar.m4f
/usr/local/share/autoconf-2.69/m4sugar/version.m4
/usr/local/share/autoconf-2.69/mdate-sh
/usr/local/share/autoconf-2.69/missing
/usr/local/share/info/autoconf.info
/usr/local/share/licenses/autoconf-2.69_3/AUTOCONF_CONFIGURE_SCRIPT_EXCEPTION
/usr/local/share/licenses/autoconf-2.69_3/GFDL
/usr/local/share/licenses/autoconf-2.69_3/GPLv2+
/usr/local/share/licenses/autoconf-2.69_3/GPLv3+
/usr/local/share/licenses/autoconf-2.69_3/LICENSE
/usr/local/share/licenses/autoconf-2.69_3/catalog.mk

**Comment by kiilerix** [comment]
Try to install `DTLSSocket==0.1.12` directly. That might give a hint towards the root cause of the problem ... which doesn't seem to be in pytradfri.
