### ISSUE TITLE
Scenes (moods) needs to be connected to a group?

### ISSUE THREAD

**Issue by OlofFredriksson** [home-assistant-libs/pytradfri#366]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
* Standalone

### Version of pytradfri
* 7.1.0

### Ikea Gateway version
* 1.15.55
### Backend used (aiocoap, libcoap)
* libcoap
### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
Linux Mint

### Expected behaviour
Gateway v1.12.31 (20th November 2020) introduced Scenes and this replaced earlier feature called  "moods". I'm very new to this library but in my understanding the scenes are not connected to groups (At least from the official ikea application point of view). Is the api in this repo not up to date regarding this Gateway update, or is it still same api, and a scene still needs to be connected to a group/room?

**Comment by OlofFredriksson** [comment]
> We haven’t touched the moods-code in a very long time so you’re probably right in that this library is not up to date. Please feel free to make the changes needed to take us back to par!

Thanks for the clarification, cannot promise anything, but i will try to see how to retrieve the scenes...

**Comment by janiversen** [comment]
from what I have and heard the API have not changed, but you never know. Best way to check is to use the IKEA app together with wireshark and dump the communication.

If you end up doing that please save the wireshark file for me, I am working on extending the test suite with actual communication in order to better test communication breakdown etc.

**Comment by ggravlingen** [comment]
In addition to the wireshark-concept: what I’ve done historically is download the android app and decompiling it (can’t remember exactly how I did it but it was fairly straightforward). The files generated from this process contains the values found in the const-file and also some, more or less, readable architecture of the app.

**Comment by janiversen** [comment]
I do not have experience with android, but that sounds very interesting. Would you be able to do it with the newest app? If you could make the files I can (with a little help from you) update the library.

I think the new gateway firmware have extra fields (looking at wireshark) and it would be nice if we could add those p.

**Comment by OlofFredriksson** [comment]
Made some more experiment and I'm actually able to retrieve all scenes/moods from the CLI so i think my previous code is wrong and this issue could be closed. Maybe the lib should rename moods to scenes to be aligned with the user applications but that is probably another question... 

Thanks for all the help!
