### ISSUE TITLE
Ikea integration needs to be reloaded

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant-libs/pytradfri#377]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant OS
### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
Raspberry Pi
### Expected behaviour
no need to have to reload the Tradfri integration all the time
### Actual behaviour
need to reload the Tradfri integration all the time.

AT first I thought this might be caused by 2021.11/dev/beta, but the linked issue mentions Ikea update to be a possible cause?

please also see: https://github.com/home-assistant/core/issues/56141

![20211103_062631000_iOS](https://user-images.githubusercontent.com/33354141/140018402-86eba8b2-6975-4329-9b7d-c5c4348f55e0.png)

also in the logs:
```
Logger: homeassistant.components.tradfri.base_class
Source: components/tradfri/base_class.py:41 
Integration: IKEA TRÅDFRI (documentation, issues) 
First occurred: 06:49:27 (6 occurrences) 
Last logged: 07:15:10

Unable to execute command <Command get ['15001', 65721]>: {"r":"01"}
Unable to execute command <Command get ['15001', 65574]>: {"r":"02"}
Unable to execute command <Command get ['15001', 65610]>: {"r":"02"}
Unable to execute command <Command get ['15001', 65720]>: {"r":"01"}
Unable to execute command <Command put ['15001', 65709]: {'3311': [{'5850': 0}]}>: ('There was an error with the request.', CredentialsMissingError('No suitable credentials for coaps://192.168.1.99:5684/15001/65709'))
```

and things like:
```
Logger: homeassistant.components.tradfri.base_class
Source: /usr/src/homeassistant/homeassistant/components/tradfri/base_class.py:87 
Integration: IKEA TRÅDFRI (documentation, issues) 
First occurred: 06:50:14 (4 occurrences) 
Last logged: 06:52:03

Observation failed for Luchtreiniger Living
Observation failed for Drawer
Observation failed for Hallway frontdoor bewegingssensor
Observation failed for Luchtreiniger Hall
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiocoap/protocol.py", line 888, in _run_observation
    weak_observation().callback(full_notification)
  File "/usr/local/lib/python3.9/site-packages/aiocoap/protocol.py", line 1034, in callback
    c(response)
  File "/usr/local/lib/python3.9/site-packages/pytradfri/api/aiocoap_api.py", line 222, in success_callback
    api_command.result = _process_output(res)
  File "/usr/local/lib/python3.9/site-packages/pytradfri/api/aiocoap_api.py", line 291, in _process_output
    raise ClientError(output)
pytradfri.error.ClientError: {"r":"01"}

```

**Comment by janiversen** [comment]
This is a problem in aiocoap.

**Comment by janiversen** [comment]
But of course it should not produce a crash.

**Comment by ggravlingen** [comment]
Should this issue really be logged here? Isn’t this an issue for the Home Assistant project?

**Comment by Mariusthvdb** [comment]
not sure, it is logged n the HA core repo, but this is logged by Pytradfri, so thought it plausible to raise here too.

Seems a stiff issue..

**Comment by Mariusthvdb** [comment]
havent seen this for some updates/resyarts anymore (though the trader still needs reloading, and even halts the startup sequence now and then)
so can probably close this?

**Comment by janiversen** [comment]
Solved with 7.2.0

**Comment by Mariusthvdb** [comment]
Hi Jan, though I closed, this, please explain what exactly was solved with 7.2.0 ?

I fear I have still been experiencing my original issue, so I am not totally confident it was solved at al.

**Comment by janiversen** [comment]
Look at the release notes.

**Comment by Mariusthvdb** [comment]
I take it you mean: https://github.com/home-assistant-libs/pytradfri/pull/378

if thats the case how can I see if this is actually used in 2021.11.5 yet?

**Comment by ggravlingen** [comment]
Check what's been released in each of the bug fix patches of HA here:
https://github.com/home-assistant/core/tags

**Comment by Mariusthvdb** [comment]
right, I thought those were for HA core , and not for the underlying libraries.
so its not merged in core yet I guess. Hence the repeated issue.
will keep open until merged then.

**Comment by Mariusthvdb** [comment]
well, its got nothing to do with the patch updates, still being 2021.11.
I believed it to be merged (and solved because of that) in 2021.12 dev, but not so unfortunately. Still happening at least 3 times a day, even with an automation triggering every 5 minutes to prevent the Bridge from being incommunicado.

If anyone is still working on this: not fixed yet in 2021.12.0.dev20211124 which should use 7.2.0

**Comment by ggravlingen** [comment]
I’ll close this as it’s related to HA and it’s implementation of pytradfri. If this library needs to be reloaded when it’s run in stand-alone mode we can open a separate issue to handle that.

**Comment by Mariusthvdb** [comment]
well, HA says its not Ha, Pytradfri says its not Pytradfri, some other experts say its aiocap, or ' incomplete underlying 3rd party protocols implementation (aiocoap).'

we need to fix 'wrongly configured spanning tree'.... this is hardly getting an clearer. SO, maybe not the correct repo in your expert opinion, others seem to differ. Where does this all leave us ? Cant we join forces on this please?
