### ISSUE TITLE
Should we switch license to Apache-2.0 from MIT?

### ISSUE THREAD

**Issue by ggravlingen** [home-assistant-libs/pytradfri#402]
@MartinHjelmare I have noted that all other libraries in `home-assistant-libs` are published under the Apache-2.0 license. `pytradfri` uses the MIT licence. I suggest we switch so that they are all the same. Are there any guidelins from the HA organisation regarding this?

**Comment by MartinHjelmare** [comment]
Not all other libs in the org uses Apache-2.0. I think it's ok to keep MIT license.

**Comment by ggravlingen** [comment]
Ok, thanks, let’s keep it as is!
