### ISSUE TITLE
Suggestions for deprecations

### ISSUE THREAD

**Issue by ggravlingen** [home-assistant-libs/pytradfri#457]
Listing the things we've been discussing to deprecate, and adding a few suggestions on my own:
- `Command._add__`: not in use?
- `Command.combine_data` not in use?
- `smart_task.StartAction.devices`: can't see this being used anywhere, nor that it adds any functionality?
- `libcoap_api`: do we really need to keep maintaining this?

**Comment by ggravlingen** [comment]
Ping @MartinHjelmare for discussion.

**Comment by MartinHjelmare** [comment]
What does the `ROOT_START_ACTION` item mean?

I think it could be ok to deprecate the libcoap api. Although currently it doesn't add very much maintenance burden either think. So I would recommend to keep it.
