### ISSUE TITLE
Libcoap depends on Aiocoap

### ISSUE THREAD

**Issue by MathiasMeuleman** [home-assistant-libs/pytradfri#475]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Stand-alone python script

### Version of pytradfri
v10.0.0

### Backend used (aiocoap, libcoap)
libcoap

### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
Running python 3.10 on Linux machine

### Expected behaviour
Imports are resolved properly, script runs as normal

### Actual behaviour
`ModuleNotFoundError: No module named 'aiocoap'` when importing `pytradfri.api.libcoap_api.APIFactory`.

In [this PR](https://github.com/home-assistant-libs/pytradfri/pull/462) a dependency on `aiocoap` was added to `libcoap`, which breaks the import. Downgrading to v9 resolves the issue.

**Comment by ggravlingen** [comment]
@MathiasMeuleman in what file is this error raised? Can you please provide the full stacktrace?

**Comment by MartinHjelmare** [comment]
This is incorrectly typed:
https://github.com/home-assistant-libs/pytradfri/blob/1d716f3f038d6409bbc2de4abda8501654781053/pytradfri/api/libcoap_api.py#L216

The libcoap api doesn't use aiocoap `Message` instances.

**Comment by MathiasMeuleman** [comment]
Here is the full stacktrace

```
Traceback (most recent call last):
  File "[...]/script.py", line 4, in <module>
    from pytradfri.api.libcoap_api import APIFactory
  File "[~]/local/lib/python3.10/site-packages/pytradfri/api/libcoap_api.py", line 10, in <module>
    from aiocoap import Message
ModuleNotFoundError: No module named 'aiocoap'
```

As @MartinHjelmare said, the dependency on `aiocoap` which imports `Message` is the culprit.

**Comment by ggravlingen** [comment]
Thanks, I’ll try to have a look at this over the weekend.

**Comment by ggravlingen** [comment]
@MathiasMeuleman 10.0.1, including the fix, is on pypi now.

**Comment by MathiasMeuleman** [comment]
Sorry for the late followup, but thank you for the quick responses and fix!
