### ISSUE TITLE
Version 2 of gateway

### ISSUE THREAD

**Issue by ggravlingen** [home-assistant-libs/pytradfri#492]
Seems like there is a version 2 of the gateway coming this fall: https://www.theverge.com/23139703/ikea-dirigera-home-smart-hub-app-price-date-specs

Will be interesting to see if this API will still work or if there's a new one on the way. 🤔

**Comment by Mariusthvdb** [comment]
cool. 
hope they will adopt multiple gateway setup in the app too, and finally allow us to cross the boundary of max 50 devices. Maybe HA should have a chat with Rebecca Töreman on the matter ;-)

**Comment by ggravlingen** [comment]
Last time I communicated with IKEA they were quite clear that we are on our own here, albeit they won't prevent us from using their internal API. Haven't head that they've changed their position in this regard unfortunately.

**Comment by MattWestb** [comment]
@ggravlingen Hej Patrik.
Do you have some working communication channel to IKEA for more technical things or can redirecting to one contact by then ?
I digging much for ZHA to getting there devices working and getting good support for them but it shall being great if can reporting problem back to them like the Styrbars latest firmware is normally reporting battery level 256 = not valid  / unknown battery reading in ZCL and its one firmware defect. Also Trådfri GW is trying updating the same device every 24 hours and failing then doing 24 hours sniffing of the network = draining batteries and im very sure they is not knowing the problem.
I looking for one very constructive feedback to them for helping both sides getting there devices working well in open system (I helping Z2M also then i can then its one part of our community but **not** DE) and in the end one win win situation for both.
I can communicating i English and Swedish and also in deeper technical terms so shall not being any problem as long its not there level 1 or 2 support then i can doing better self.

Mvh  Mattias W

**Comment by ggravlingen** [comment]
> @ggravlingen Hej Patrik.
> 
> Do you have some working communication channel to IKEA for more technical things or can redirecting to one contact by then ?
> 
> I digging much for ZHA to getting there devices working and getting good support for them but it shall being great if can reporting problem back to them like the Styrbars latest firmware is normally reporting battery level 256 = not valid  / unknown battery reading in ZCL and its one firmware defect. Also Trådfri GW is trying updating the same device every 24 hours and failing then doing 24 hours sniffing of the network = draining batteries and im very sure they is not knowing the problem.
> 
> I looking for one very constructive feedback to them for helping both sides getting there devices working well in open system (I helping Z2M also then i can then its one part of our community but **not** DE) and in the end one win win situation for both.
> 
> I can communicating i English and Swedish and also in deeper technical terms so shall not being any problem as long its not there level 1 or 2 support then i can doing better self.
> 
> 
> 
> Mvh  Mattias W


Hi, long story short: I haven't been in touch with IKEA in years. Last time I did they were very frank that they were fine with us using their internal API (which is what we do here), but they wouldn't support us in any way. I have not heard that they have changed stances on this.

However, I had a look at the LinkedIn profile of the person I was in touch with and he seems to have left IKEA for another company recently.

My best advice is to see if the much more powerful parent organization to this repo (Home Assisant) have any connections on the inside. Maybe @MartinHjelmare would have heard of any such high-level talks?

**Comment by MattWestb** [comment]
Thanks for replay and information.
I dont knowing how is the official CSA-IOT for HA / NC but our Silabs-addon dev was on the Zigbee meeting and the IKEA repentant is the coordinator for CSA-IOT group Europe (its only 2 the next is China) so can also being one road getting one contact in the right level and not too high but OK from the top.

I think what I / we (ZHA) can giving good feed back for getting there product working better and also helping testing new device firmware if they like. But it shall being better then GIRIGERA is using normal coordinator as we is doing so the is getting the same problem (TF was one "ZLL controller bridge" and different  working mode).
Also its likely coming Thread and / or Matter devices from them and also can being good for both sides have good communication with constructive feedback.

**Comment by puddly** [comment]
@MattWestb I can try to get in touch with some IKEA engineers for you through the CSA. Do you have any links to specific firmware problems (or just one major one) that I can summarize for them? If you want, send me an email (`puddly3@gmail.com`) and we can discuss further.

**Comment by MattWestb** [comment]
Thanks our **Puddly**  I must looking for what is good reporting but i getting friend visiting in 10 hours so i must do it later but i dont forgetting it.

Styrbar is reporting battery 255 in later version and its out or range / not valid / not known but i must looking for issue but i think its in Z2M we was disusing it but i mailing you (to "3") that i have checking it.

**Comment by Mariusthvdb** [comment]
If you do get in touch, it would be awesome if the other ( for gateway gen 1) and ever pestering issue could be discussed too...

**Comment by MattWestb** [comment]
Make one issue if not one is made and mailing the link to **Puddly** and hi can trying contacting them.

For TF GW we cant hoping so much more then some bug fixes and some new devices like upcoming the RGBWW LED strip controller but not the Window / Door sensor then its not fitting well with the ZLL controller bridge ground functionality.

IKEA highest priority is getting the Matter bridge function in Diregera and then more devices and functionality in it like getting Thread devices on boarded after Matter bridge functionality..

**Comment by ggravlingen** [comment]
Thanks @puddly!
