### ISSUE TITLE
No discovery of supergroups to control Tradfri scenes as defined in the IKEA app

### ISSUE THREAD

**Issue by klausb** [home-assistant-libs/pytradfri#616]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home assistant
### Version of pytradfri
Most recent version loaded from HA
### Backend used (aiocoap, libcoap)
don't know
### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)
VM in proxmox
### Expected behaviour
Find supergroups as entities
### Actual behaviour
Supergroups are not discovered. I have a parallel deployment of ioBroker and I see them there.
Main reason: with supergroups I'm able to select Tradfri scenes, defined in the IKEA app

**Comment by MartinHjelmare** [comment]
What's a supergroup?

**Comment by klausb** [comment]
Hi @MartinHjelmare, the IKEA tradfri app allows you to create scenes as groups of lights and plugs. They can be activated in the app or via the shortcut button.
Looking at the discovery of tradfri by ioBroker, a so-called supergroup entity is created which allows to monitor and activate such a scene, by setting the activeScene property. I'm wondering if HA can discover them, since ioBroker does.

There is no list of scenes, but you can read them out, once you start a scene. Later setting the scene programmatically activates it.

Interestingly, some HA users got them discovered, but had no clue what it is. See here: https://community.home-assistant.io/t/supergroup/254758. Unfortunately, I can't see them in my HA deployment.

I looked up the nodejs code used by ioBroker which observes groups and scenes: https://github.com/AlCalzone/node-tradfri-client/blob/a63135810c09531fb0500efd2c23c460f9f81b5e/src/tradfri-client.ts#L547.

Below is a screenshot on what ioBroker discovers
<img width="862" alt="image" src="https://user-images.githubusercontent.com/209846/213859620-28b01028-0344-4456-a771-be74eb7c46a9.png">

**Comment by MartinHjelmare** [comment]
We don't have support for Scenes yet in pytradfri. We support Groups and we support Moods for Groups.

Groups are not supported anymore in Home Assistant as they were not deemed reliable when communicating with the gateway.

Scenes is a relatively new feature in the Tradfri app while Groups and Moods have been around for a long time. PRs for Scene support for pytradfri is welcome.

When I try creating a Scene in the Tradfri app it first removed my Moods. Maybe they are related somehow in the Tradfri protocol?

**Comment by MartinHjelmare** [comment]
According to this issue, Moods and Scenes can be retrieved by using the Mood api in pytradfri:

https://github.com/home-assistant-libs/pytradfri/issues/366

**Comment by klausb** [comment]
It seems moods have been replaced by scenes. But they are not exposed in HA.
You mentioned moods for groups are supported. How can I see them in HA?

**Comment by MartinHjelmare** [comment]
Moods are not supported by Home Assistant but they are supported here in pytradfri.

The Dirigera hub reportedly works with the Homekit Controller integration in Home Assistant. I haven't tested it myself.
