### ISSUE TITLE
multiple errors mentioning Pytradfri

### ISSUE THREAD

**Issue by Mariusthvdb** [home-assistant-libs/pytradfri#617]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)
Home Assistant OS

not really sure how to log this, but ever since the 2023.1 beta cycle we see huge amounts of Tradfri errors, some of them mentioning Pytradfri, some only logging homeassistant.components.tradfri.

Ive opened an issue in [Core](https://github.com/home-assistant/core/issues/85254),  but realized it might be useful to post here too. 

I guess I should not copy all of that issue here, to prevent to much noise.
Without further instructions, Ill await your response, and hope you might be able to give some pointers how to proceed.

All of the below headers might not be useful to fill put, since this is happening on a core HAOS install, without anything further.

If this is the wrong place, I apologize, and feel free to close.

**Comment by MartinHjelmare** [comment]
No need to open an issue here if there's an issue in Home Assistant already opened.

Side note: Nothing significant has changed in the tradfri integration in recent releases. You can see that by looking at the commits in the master branch at this time:

https://github.com/home-assistant/core/commits/master/homeassistant/components/tradfri
