### ISSUE TITLE
Dev_docker approach is not working

### ISSUE THREAD

**Issue by SpeedyR10** [home-assistant-libs/pytradfri#618]
Hi, 
I'm using windows 10 and I'm trying to use the dev_docker approach since I couldn't also use the standalone one.

1st STAND-ALONE (CLI) Local python version 3.11.1
![tradfri](https://user-images.githubusercontent.com/59510273/214047081-29705b3e-d8a0-4f61-be4f-a0a857cc7c71.png)

2nd DEV_DOCKER APPROACH
![image](https://user-images.githubusercontent.com/59510273/214044307-2996c58f-bbe7-4460-b6f5-c2c4c398ec4a.png)

I'm not an expert on docker but this image is not in any registry i believe, hence the error.

I tried it with another like 3.11.1 and did get further:
![image](https://user-images.githubusercontent.com/59510273/214045765-8f226cd3-5250-41c6-8c8c-cfbc8c74f541.png)

But still got an error of a missing file: "/usr/src/app/script/install-coap-client.sh: not found"

Any help?

**Comment by ggravlingen** [comment]
Nor [Windows](https://github.com/home-assistant-libs/pytradfri/issues/235) or Python 3.11 are supported unfortunately.

Seems like stretch is no longer supported by the Python docker repo. Try replacing `3.10-stretch` with `3.10-bullseye` and see if that works.

**Comment by SpeedyR10** [comment]
Thank you for the fast answer. It doesn't work also, no

**Comment by ggravlingen** [comment]
Personally, I'm running this in VS code using a containerized dev environment. If you enable that excention in VS Code and open this repo, you will be prompted to the library in a containerized environment.

**Comment by SpeedyR10** [comment]
Hi again!

Tried it and i think the error of missing file persists even when using the containerized dev environment of vscode. Below is the log:

![image](https://user-images.githubusercontent.com/59510273/214181744-06d6cf62-b98a-4345-b455-4c0694f959e7.png)

Let me know if there's something i'm missing.

**Comment by ggravlingen** [comment]
> Hi again!
> 
> Tried it and i think the error of missing file persists even when using the containerized dev environment of vscode. Below is the log:
> 
> ![image](https://user-images.githubusercontent.com/59510273/214181744-06d6cf62-b98a-4345-b455-4c0694f959e7.png)
> 
> Let me know if there's something i'm missing.

I just tried it myself on my Mac and it started as expected. Are you running VS Code on Windows or in WSL2?

**Comment by SpeedyR10** [comment]
On Windows 10

**Comment by ggravlingen** [comment]
You might have to install WSL2 or run VS Code on Linux in a VM like VirtualBox.

I will close this issue now as the error is unrelated to this library.
