### ISSUE TITLE
Request to gateway times out

### ISSUE THREAD

**Issue by SpeedyR10** [home-assistant-libs/pytradfri#619]
Environment: Linux Ubuntu VIrtual Machine

Got it running inside a dev container but it keeps timing out when i try to use the pair example, just when it tries to connect to the gateway.

![Untitled](https://user-images.githubusercontent.com/59510273/214445442-9d5c1cd2-e418-40f6-896c-a0c6010aa155.png)

I confirmed the IP on my router:

![image](https://user-images.githubusercontent.com/59510273/214445628-7c797d63-9aff-4193-bc5a-81391ff429eb.png)

Also tried to ping this IP from the container and it could

Rescanned the QR Code on the bottom to double check the security code.

Cant see where i might be wrong. Can you help me?

**Comment by SpeedyR10** [comment]
My version of the gateway is E2003 DIRIGERA. Can this be the problem?

**Comment by MartinHjelmare** [comment]
The DIRIGERA hub is not supported.

**Comment by SpeedyR10** [comment]
oh ok. took me a while to understand that, sorry and thank you for the help regardless
