### ISSUE TITLE
No support for DIRIGERA gayway, TRADFRI is deprecated

### ISSUE THREAD

**Issue by hnsl** [home-assistant-libs/pytradfri#639]
The TRADFRI gatway is deprecated and not sold anymore. It has been superseded by the DIRIGERA gayway. This library does not support the DIRIGERA gatway.

See: https://github.com/dvdgeisler/DirigeraClient

**Comment by ggravlingen** [comment]
That is correct, this library supports the old gateway only.

**Comment by Mariusthvdb** [comment]
Hey Patrik,

Are you still maintainer of the integration? because we have heavy issues, and it would really be great if someone would check these out, if only to guide us in debugging them

**Comment by ggravlingen** [comment]
I'm one of the maintainers of this library, but not of the Home Assistant integration. I stopped being an active maintainer many years ago.
