### ISSUE TITLE
pydantic error type=missing

### ISSUE THREAD

**Issue by dylaninbcky** [home-assistant-libs/pytradfri#831]
### Where are you using pytradfri (eg stand-alone, Home Assistant etc)

stand alone

### Version of pytradfri

newest one

### Backend used (aiocoap, libcoap)

libcoap

### What type of environment are you in, eg Dockerized, Raspberry PI, VirtualBox, WiFi network (give as much details as possible)

running on Ubuntu VM

----

When running the example scripts im getting a pydantic error that im missing the Type.
see below. Does anyone have any idea how to fix?

15025
  Field required [type=missing, input_value={'9001': 'Kledingkamer li...: 'd9337c', '9003': 0}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
15015
  Field required [type=missing, input_value={'9001': 'Kledingkamer li...: 'd9337c', '9003': 0}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
3.9
  Field required [type=missing, input_value={'0': 'IKEA of Sweden', '...: 1, '7': 10242, '8': 4}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
15014
  Field required [type=missing, input_value={'9001': 'Kledingkamer li...: 'd9337c', '9003': 0}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
3312
  Field required [type=missing, input_value={'9001': 'Kledingkamer li...: 'd9337c', '9003': 0}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing

**Comment by ggravlingen** [comment]
This seems somewhat related to this error: https://github.com/home-assistant-libs/pytradfri/issues/810

**Comment by dylaninbcky** [comment]
yes those are lightbulbs, but when i first tried it i got other lightbulbs in the error message. i thought maybe those were causing the error because they are not in my house anymore. so i deleted them from the app. These lightbulbs however, are up and running and firmware updated.

these are the versions of pydantic that i'm running!
pydantic               1.10.14
pydantic_core          2.16.3

**Comment by ggravlingen** [comment]
Odd, those missing fields are referring to air purifier (15025), and blinds (15015) among other things (https://github.com/home-assistant-libs/pytradfri/blob/master/pytradfri/const.py).

Can you please provide the whole stack trace for the error?

**Comment by dylaninbcky** [comment]
hey, the oddness continues haha. i just logged in to try and send you the stack trace. however now the errors are not popping up anymore. i've had this issue for 5 days straight but for some reason it started working just now,

If the fault will pop up again. i will open a new issue and post the whole stack trace. 

Thank you for helping ggravlingen :)
